"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var User_1 = require("./User");
Object.defineProperty(exports, "UserModel", { enumerable: true, get: function () { return User_1.default; } });
var Dialog_1 = require("./Dialog");
Object.defineProperty(exports, "DialogModel", { enumerable: true, get: function () { return Dialog_1.default; } });
var Message_1 = require("./Message");
Object.defineProperty(exports, "MessageModel", { enumerable: true, get: function () { return Message_1.default; } });
var UploadFile_1 = require("./UploadFile");
Object.defineProperty(exports, "UploadFileModel", { enumerable: true, get: function () { return UploadFile_1.default; } });
